[package]
name = "blog_os"
version = "0.0.1"
authors = ["Harrisonn <j.h.m.t.v.10@gmail.com>"]
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
